# Generated by Django 5.2.3 on 2025-07-11 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PorosityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название анализа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('original_image_uuid', models.CharField(max_length=36, unique=True, verbose_name='UUID исходного изображения')),
                ('results_uuid', models.CharField(max_length=36, unique=True, verbose_name='UUID результатов')),
                ('scale_value', models.FloatField(verbose_name='Значение шкалы (мкм)')),
                ('pixels_per_micron', models.FloatField(blank=True, null=True, verbose_name='Пикселей на микрометр')),
                ('porosity_percentage', models.FloatField(blank=True, null=True, verbose_name='Процент пористости')),
                ('number_of_pores', models.IntegerField(blank=True, null=True, verbose_name='Количество пор')),
                ('average_pore_size', models.FloatField(blank=True, null=True, verbose_name='Средний размер пор (мкм)')),
                ('max_pore_size', models.FloatField(blank=True, null=True, verbose_name='Максимальный размер пор (мкм)')),
                ('min_pore_size', models.FloatField(blank=True, null=True, verbose_name='Минимальный размер пор (мкм)')),
                ('pore_density', models.FloatField(blank=True, null=True, verbose_name='Плотность пор (пор/мкм²)')),
                ('average_interpore_distance', models.FloatField(blank=True, null=True, verbose_name='Среднее межпоровое расстояние (мкм)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершен'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
            ],
            options={
                'verbose_name': 'Анализ пористости',
                'verbose_name_plural': 'Анализы пористости',
                'db_table': 'porosity_analysis',
                'ordering': ['-created_at'],
            },
        ),
    ]
