# Generated by Django 5.2.2 on 2025-06-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppearanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(default='default', max_length=100, verbose_name='Название темы')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Конфигурация темы')),
            ],
            options={
                'verbose_name': 'Настройки внешнего вида',
                'verbose_name_plural': 'Настройки внешнего вида',
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, max_length=255, verbose_name='SMTP Host')),
                ('smtp_port', models.PositiveIntegerField(default=25, verbose_name='SMTP Port')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='SMTP Username')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='SMTP Password')),
                ('default_from', models.EmailField(blank=True, max_length=254, verbose_name='Default From Email')),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
        migrations.CreateModel(
            name='MediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_upload_size', models.PositiveIntegerField(default=5242880, help_text='Максимальный размер загружаемого файла', verbose_name='Max Upload Size (bytes)')),
                ('allowed_file_types', models.CharField(default='jpg,jpeg,png,gif,svg,mp4,mp3,pdf', help_text='Через запятую, без точек', max_length=255, verbose_name='Allowed File Extensions')),
            ],
            options={
                'verbose_name': 'Media Settings',
                'verbose_name_plural': 'Media Settings',
            },
        ),
        migrations.CreateModel(
            name='PermalinkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(default='/%year%/%month%/%slug%/', help_text='Например: /%year%/%month%/%slug%/', max_length=255, verbose_name='URL Structure')),
            ],
            options={
                'verbose_name': 'Permalink Settings',
                'verbose_name_plural': 'Permalink Settings',
            },
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_backup', models.BooleanField(default=True, help_text='Показывать кнопку резервного копирования', verbose_name='Enable Backup')),
                ('last_backup', models.DateTimeField(blank=True, null=True, verbose_name='Last Backup Time')),
            ],
            options={
                'verbose_name': 'Security Settings',
                'verbose_name_plural': 'Security Settings',
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title_template', models.CharField(default='%page_title% | %site_name%', help_text="Шаблон заголовка, например: '%page_title% | %site_name%'", max_length=255, verbose_name='Шаблон мета-заголовка')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета-описание')),
                ('analytics_script', models.TextField(blank=True, help_text='Код для вставки (Google Analytics, Яндекс.Метрика и т.д.)', verbose_name='Скрипт для аналитики')),
            ],
            options={
                'verbose_name': 'SEO найтройки',
                'verbose_name_plural': 'SEO настройки',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Site', max_length=255, verbose_name='Название сайта')),
                ('site_tagline', models.CharField(blank=True, max_length=255, verbose_name='Tagline')),
                ('site_url', models.URLField(verbose_name='URL сайта')),
                ('admin_email', models.EmailField(max_length=254, verbose_name='Email администратора')),
                ('homepage_type', models.CharField(choices=[('static', 'Статическая страница'), ('latest', 'Последние сообщения')], default='latest', max_length=10, verbose_name='Тип домашней страницы')),
                ('posts_per_page', models.PositiveIntegerField(default=10, verbose_name='Посты на страницу')),
                ('discourage_search_engines', models.BooleanField(default=False, help_text='Запретить индексацию сайта', verbose_name='Discourage Search Engines')),
                ('privacy_policy', models.TextField(blank=True, verbose_name='Политика конфиденциальности')),
                ('roles', models.ManyToManyField(blank=True, help_text='Группы пользователей, доступных в системе', to='auth.group', verbose_name='Роли пользователей')),
            ],
            options={
                'verbose_name': 'Общие настройки',
                'verbose_name_plural': 'Общие настройки',
            },
        ),
    ]
