# Generated by Django 5.2.2 on 2025-06-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_delete_seosettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='alt_name',
            field=models.CharField(blank=True, help_text='Понятное пользователю название файла', max_length=255, verbose_name='Альтернативное название'),
        ),
    ]
