# Generated by Django 5.2.3 on 2025-06-28 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_auto_create_default_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='site_icon',
            field=models.ImageField(blank=True, help_text='Иконка сайта (favicon). Рекомендуемые форматы: .ico, .png. Размер: 32x32 или 16x16 пикселей.', null=True, upload_to='site_icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png', 'jpg', 'jpeg', 'gif', 'svg'])], verbose_name='Иконка сайта'),
        ),
    ]
