# Generated by Django 5.2.3 on 2025-06-28 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_generalsettings_site_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='site_icon',
            field=models.ImageField(blank=True, help_text='Favicon сайта. Рекомендуемый размер: 32x32 или 16x16 пикселей. Поддерживаемые форматы: ICO, PNG, JPG, SVG', null=True, upload_to='site_icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png', 'jpg', 'jpeg', 'svg'])], verbose_name='Иконка сайта'),
        ),
    ]
