# Generated by Django 5.2.3 on 2025-06-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_alter_generalsettings_site_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='site_icon',
        ),
    ]
