# Generated by Django 5.2.3 on 2025-06-28 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_remove_generalsettings_site_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='site_icon',
            field=models.ImageField(blank=True, help_text='Иконка сайта (favicon). Рекомендуемый размер: 32x32 или 64x64 пикселей', null=True, upload_to='site_icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'ico'])], verbose_name='Иконка сайта'),
        ),
    ]
