# Generated by Django 5.2.3 on 2025-06-28 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_generalsettings_site_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='site_icon',
            field=models.ForeignKey(blank=True, help_text='Иконка сайта (favicon). Рекомендуемый размер: 32x32 или 64x64 пикселей', null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.uploadedfile', verbose_name='Иконка сайта'),
        ),
    ]
