# Generated by Django 5.1.7 on 2025-05-18 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_expansion', '0006_fileupload_group_filegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCoords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_left_latitude', models.FloatField()),
                ('upper_left_longitude', models.FloatField()),
                ('down_right_latitude', models.FloatField()),
                ('down_right_longitude', models.FloatField()),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cities_expansion.group')),
            ],
        ),
    ]
