# Generated by Django 5.2.4 on 2025-07-30 08:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FgosParsingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время начала')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('total_pages_found', models.IntegerField(default=0, verbose_name='Всего найдено страниц')),
                ('total_documents_found', models.IntegerField(default=0, verbose_name='Всего найдено документов')),
                ('new_documents_added', models.IntegerField(default=0, verbose_name='Добавлено новых документов')),
                ('documents_updated', models.IntegerField(default=0, verbose_name='Обновлено документов')),
                ('files_downloaded', models.IntegerField(default=0, verbose_name='Скачано файлов')),
                ('download_errors', models.IntegerField(default=0, verbose_name='Ошибок скачивания')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], default='running', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
            ],
            options={
                'verbose_name': 'Сессия парсинга ФГОС',
                'verbose_name_plural': 'Сессии парсинга ФГОС',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FgosDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID файла')),
                ('title', models.CharField(max_length=500, verbose_name='Название ФГОС')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код специальности')),
                ('level', models.CharField(blank=True, max_length=100, null=True, verbose_name='Уровень образования')),
                ('field_of_study', models.CharField(blank=True, max_length=200, null=True, verbose_name='Область изучения')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Размер файла в байтах')),
                ('source_url', models.URLField(verbose_name='Исходная ссылка на страницу')),
                ('download_url', models.URLField(verbose_name='Ссылка для скачивания PDF')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('parsed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время парсинга')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_downloaded', models.BooleanField(default=False, verbose_name='Файл скачан')),
                ('download_error', models.TextField(blank=True, null=True, verbose_name='Ошибка скачивания')),
                ('order_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер приказа')),
                ('ministry', models.CharField(blank=True, max_length=200, null=True, verbose_name='Министерство')),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регистрационный номер')),
            ],
            options={
                'verbose_name': 'Документ ФГОС',
                'verbose_name_plural': 'Документы ФГОС',
                'ordering': ['-parsed_at'],
                'indexes': [models.Index(fields=['code'], name='education_m_code_4b9dc3_idx'), models.Index(fields=['level'], name='education_m_level_fee964_idx'), models.Index(fields=['parsed_at'], name='education_m_parsed__0289c7_idx'), models.Index(fields=['is_downloaded'], name='education_m_is_down_f3360f_idx')],
            },
        ),
    ]
