# Generated by Django 5.1.7 on 2025-05-28 10:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning_analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код дисциплины')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(max_length=400, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Базовая дисциплина',
                'verbose_name_plural': 'Базовые дисциплины',
                'db_table': 'la_df_base_discipline',
            },
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=400)),
                ('know_level', models.TextField(help_text='Теоретические знания', verbose_name='Знать')),
                ('can_level', models.TextField(help_text='Практические навыки', verbose_name='Уметь')),
                ('master_level', models.TextField(help_text='Способность к выполнению задач', verbose_name='Владеть')),
                ('blooms_level', models.CharField(choices=[('KNOW', 'Знание'), ('UNDERSTAND', 'Понимание'), ('APPLY', 'Применение'), ('ANALYZE', 'Анализ'), ('EVALUATE', 'Оценка'), ('CREATE', 'Создание')], default='KNOW', verbose_name='Уровень таксономии Блума')),
                ('blooms_verbs', models.CharField(help_text='Через запятую: анализировать, оценивать, создавать и т.д.', max_length=255, verbose_name='Глаголы для оценки таксономии Блума')),
                ('complexity', models.PositiveIntegerField(default=5, help_text='Сложность компетенции от 1 до 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Сложность')),
                ('demand', models.PositiveIntegerField(default=5, help_text='Востребованность компетенции от 1 до 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Востребованность')),
            ],
            options={
                'verbose_name': 'Компетенция',
                'verbose_name_plural': 'Компетенции',
                'db_table': 'la_df_competency',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_duration', models.PositiveSmallIntegerField(verbose_name='Срок получения образования')),
                ('year_of_admission', models.CharField(max_length=4, verbose_name='Год поступления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность учебного плана')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебные планы',
                'db_table': 'la_df_curriculum',
            },
        ),
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время импорта')),
                ('data_type', models.CharField(choices=[('curriculum', 'Учебный план'), ('competencies', 'Компетенции'), ('technologies', 'Технологии'), ('vacancies', 'Вакансии'), ('custom', 'Пользовательский формат')], max_length=50, verbose_name='Тип данных')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('records_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество записей')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('warning', 'С предупреждениями'), ('error', 'С ошибками')], max_length=20, verbose_name='Статус импорта')),
            ],
            options={
                'verbose_name': 'История импорта',
                'verbose_name_plural': 'История импортов',
                'db_table': 'la_df_import_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ImportStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_of_imported_files', models.PositiveIntegerField(default=0, verbose_name='Количество импортированных файлов')),
                ('sum_of_imported_records', models.PositiveIntegerField(default=0, verbose_name='Количество импортированных записей')),
                ('last_file_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последнего импортированного файла')),
            ],
            options={
                'verbose_name': 'Статистика импорта данных',
                'verbose_name_plural': 'Статистика импорта данных',
                'db_table': 'la_df_import_stats',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код специальности')),
                ('name', models.CharField(max_length=255, verbose_name='Специальность')),
                ('specialization', models.CharField(max_length=255, verbose_name='Специализация')),
                ('department', models.CharField(max_length=255, verbose_name='Кафедра')),
                ('faculty', models.CharField(max_length=255, verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'db_table': 'la_df_speciality',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=400)),
                ('popularity', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
                'db_table': 'la_df_technology',
            },
        ),
        migrations.CreateModel(
            name='UCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveSmallIntegerField(verbose_name='ID пользователя')),
                ('competencies_stack', models.JSONField(verbose_name='Перечень имеющихся компетенций')),
                ('technology_stack', models.JSONField(verbose_name='Стек изучаемых технологий')),
            ],
            options={
                'verbose_name': 'Матрица компетенций пользователя',
                'verbose_name_plural': 'Матрицы компетенций пользователей',
                'db_table': 'la_df_user_competency_matrix',
            },
        ),
        migrations.CreateModel(
            name='ACM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_list', models.JSONField(verbose_name='Перечень изучаемых дисциплин')),
                ('technology_stack', models.JSONField(verbose_name='Перечень изучаемых технологий в течение времени')),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_analytics_data_formalization_submodule.curriculum', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Матрица академических компетенций',
                'verbose_name_plural': 'Матрицы академических компетенций',
                'db_table': 'la_df_academic_competence_matrix',
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_analytics_data_formalization_submodule.speciality', verbose_name='Специальность'),
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код дисциплины')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('semesters', models.CharField(max_length=12, verbose_name='Период освоения (семестры)')),
                ('contact_work_hours', models.PositiveSmallIntegerField(verbose_name='Контактная работа, ч')),
                ('independent_work_hours', models.PositiveSmallIntegerField(verbose_name='Самостоятельная работа, ч')),
                ('control_work_hours', models.PositiveSmallIntegerField(verbose_name='Контроль, ч')),
                ('base_discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_discipline', to='learning_analytics_data_formalization_submodule.basediscipline', verbose_name='Базовая дисциплина')),
                ('competencies', models.ManyToManyField(blank=True, db_table='la_df_disc_comp_rel', related_name='disciplines', to='learning_analytics_data_formalization_submodule.competency', verbose_name='Компетенции')),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_disciplines', to='learning_analytics_data_formalization_submodule.curriculum', verbose_name='Учебный план')),
                ('technologies', models.ManyToManyField(blank=True, db_table='la_df_disc_tech_rel', related_name='disciplines', to='learning_analytics_data_formalization_submodule.technology', verbose_name='Технологии')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'db_table': 'la_df_discipline',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Обязанности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Минимальная зарплата')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальная зарплата')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Местоположение')),
                ('employment_type', models.CharField(choices=[('FULL', 'Полная занятость'), ('PART', 'Частичная занятость'), ('REMOTE', 'Удаленная работа')], default='FULL', max_length=10, verbose_name='Тип занятости')),
                ('competencies', models.ManyToManyField(blank=True, db_table='la_df_vacancy_comp_rel', related_name='vacancies', to='learning_analytics_data_formalization_submodule.competency', verbose_name='Компетенции')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='learning_analytics.employer', verbose_name='Работодатель')),
                ('technologies', models.ManyToManyField(blank=True, db_table='la_df_vacancy_tech_rel', related_name='vacancies', to='learning_analytics_data_formalization_submodule.technology', verbose_name='Технологии')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'la_df_vacancy',
            },
        ),
        migrations.CreateModel(
            name='VCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=400, verbose_name='Описание профиля компетенций')),
                ('competencies', models.ManyToManyField(blank=True, db_table='la_df_vcm_comp_rel', related_name='vcm_profiles', to='learning_analytics_data_formalization_submodule.competency', verbose_name='Компетенции')),
                ('technologies', models.ManyToManyField(blank=True, db_table='la_df_vcm_tech_rel', related_name='vcm_profiles', to='learning_analytics_data_formalization_submodule.technology', verbose_name='Технологии')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vcm_profiles', to='learning_analytics_data_formalization_submodule.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Компетентностный профиль вакансии',
                'verbose_name_plural': 'Компетентностные профили вакансии',
                'db_table': 'la_df_competency_profile_of_vacancy',
            },
        ),
    ]
