# Generated by Django 5.2.4 on 2025-07-30 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperJobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('salary_from', models.IntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.IntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('salary_currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Валюта зарплаты')),
                ('salary_gross', models.BooleanField(default=True, verbose_name='Зарплата до вычета налогов')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Требования')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='Обязанности')),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип занятости')),
                ('experience_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Уровень опыта')),
                ('skills', models.JSONField(default=list, verbose_name='Навыки')),
                ('key_skills', models.JSONField(default=list, verbose_name='Ключевые навыки')),
                ('superjob_id', models.CharField(max_length=50, unique=True, verbose_name='ID вакансии на SuperJob')),
                ('url', models.URLField(verbose_name='Ссылка на вакансию')),
                ('company_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на компанию')),
                ('schedule_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='График работы')),
                ('professional_role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Профессиональная роль')),
                ('alternate_url', models.URLField(blank=True, null=True, verbose_name='Альтернативная ссылка')),
                ('apply_alternate_url', models.URLField(blank=True, null=True, verbose_name='Ссылка для отклика')),
                ('employer_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID работодателя')),
                ('employer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название работодателя')),
                ('employer_trusted', models.BooleanField(default=False, verbose_name='Проверенный работодатель')),
                ('employer_blacklisted', models.BooleanField(default=False, verbose_name='Работодатель в черном списке')),
                ('premium', models.BooleanField(default=False, verbose_name='Премиум вакансия')),
                ('has_test', models.BooleanField(default=False, verbose_name='Есть тестовое задание')),
                ('response_letter_required', models.BooleanField(default=False, verbose_name='Требуется сопроводительное письмо')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('current_version', models.IntegerField(default=1, verbose_name='Текущая версия')),
            ],
            options={
                'verbose_name': 'Вакансия SuperJob',
                'verbose_name_plural': 'Вакансии SuperJob',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['title'], name='vacancies_p_title_cd8ce7_idx'), models.Index(fields=['company_name'], name='vacancies_p_company_3fd3b5_idx'), models.Index(fields=['city'], name='vacancies_p_city_6a5a90_idx'), models.Index(fields=['published_at'], name='vacancies_p_publish_48800a_idx'), models.Index(fields=['superjob_id'], name='vacancies_p_superjo_65b74d_idx'), models.Index(fields=['employer_id'], name='vacancies_p_employe_bf3c34_idx'), models.Index(fields=['current_version'], name='vacancies_p_current_74ba20_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuperJobVacancyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='Номер версии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания версии')),
                ('change_summary', models.TextField(blank=True, null=True, verbose_name='Описание изменений')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='vacancies_parser_superjob.superjobvacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Версия вакансии SuperJob',
                'verbose_name_plural': 'Версии вакансий SuperJob',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='SuperJobVacancyChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Название поля')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Новое значение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='vacancies_parser_superjob.superjobvacancy', verbose_name='Вакансия')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='vacancies_parser_superjob.superjobvacancyversion', verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'История изменений вакансии SuperJob',
                'verbose_name_plural': 'История изменений вакансий SuperJob',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='superjobvacancyversion',
            index=models.Index(fields=['vacancy', 'version_number'], name='vacancies_p_vacancy_4d599c_idx'),
        ),
        migrations.AddIndex(
            model_name='superjobvacancyversion',
            index=models.Index(fields=['created_at'], name='vacancies_p_created_447215_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='superjobvacancyversion',
            unique_together={('vacancy', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='superjobvacancychangehistory',
            index=models.Index(fields=['vacancy', 'created_at'], name='vacancies_p_vacancy_5f7612_idx'),
        ),
        migrations.AddIndex(
            model_name='superjobvacancychangehistory',
            index=models.Index(fields=['field_name'], name='vacancies_p_field_n_4da4cd_idx'),
        ),
    ]
