# Generated by Django 5.1.7 on 2025-04-15 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bi_analysis_bi_datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('chart_type', models.CharField(choices=[('line', 'Линейная диаграмма'), ('area', 'Диаграмма с областями'), ('area_stacked', 'Нормированная диаграмма с областями'), ('bar', 'Столбчатая диаграмма'), ('bar_stacked', 'Нормированная столбчатая диаграмма'), ('line_bar', 'Линейчатая диаграмма'), ('line_bar_stacked', 'Нормированная линейчатая диаграмма'), ('scatter', 'Точечная диаграмма'), ('pie', 'Круговая диаграмма'), ('donut', 'Кольцевая диаграмма'), ('indicator', 'Индикатор'), ('tree', 'Древовидная диаграмма'), ('table', 'Таблица'), ('pivot', 'Сводная таблица'), ('map', 'Карта'), ('combo', 'Комбинированная диаграмма')], max_length=32)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='bi_analysis_bi_datasets.dataset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
