# Generated by Django 5.2.3 on 2025-06-15 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_analysis_bi_charts', '0001_initial'),
        ('bi_analysis_bi_datasets', '0009_datasettable_columns_info_datasettable_display_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='config',
        ),
        migrations.AddField(
            model_name='chart',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chart',
            name='engine',
            field=models.CharField(default='apex', max_length=32),
        ),
        migrations.AddField(
            model_name='chart',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chart',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='chart_type',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='chart',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi_analysis_bi_datasets.dataset'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='chart',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charts', to=settings.AUTH_USER_MODEL),
        ),
    ]
