# Generated by Django 5.2.3 on 2025-06-29 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название программы')),
                ('year', models.IntegerField(verbose_name='Год программы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Программа развития',
                'verbose_name_plural': 'Программы развития',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование этапа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('planned_start_date', models.DateField(verbose_name='Плановая дата начала')),
                ('planned_end_date', models.DateField(verbose_name='Плановая дата окончания')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата начала')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата окончания')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('delayed', 'Просрочен')], default='planned', max_length=20, verbose_name='Статус этапа')),
                ('expected_results', models.JSONField(default=list, verbose_name='Ожидаемые результаты')),
                ('target_indicators', models.JSONField(default=list, verbose_name='Целевые показатели')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Бюджет этапа')),
                ('order_number', models.IntegerField(verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Этап проекта',
                'verbose_name_plural': 'Этапы проекта',
                'ordering': ['project', 'order_number'],
            },
        ),
        migrations.CreateModel(
            name='ProgramTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_code', models.CharField(max_length=50, verbose_name='Код направления')),
                ('topic_number', models.CharField(max_length=50, verbose_name='Номер темы')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование темы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('planned_start_date', models.DateField(verbose_name='Плановая дата начала')),
                ('planned_end_date', models.DateField(verbose_name='Плановая дата окончания')),
                ('expected_results', models.JSONField(default=list, verbose_name='Ожидаемые результаты')),
                ('status', models.CharField(choices=[('free', 'Свободно'), ('reserved', 'Занято')], default='free', max_length=20, verbose_name='Статус')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='crm_strategic_projects.developmentprogram')),
            ],
            options={
                'verbose_name': 'Тема программы развития',
                'verbose_name_plural': 'Темы программы развития',
            },
        ),
        migrations.CreateModel(
            name='StageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание результата')),
                ('result_type', models.CharField(choices=[('document', 'Документ'), ('product', 'Продукт'), ('service', 'Услуга'), ('other', 'Прочее')], max_length=20, verbose_name='Тип результата')),
                ('files', models.JSONField(default=list, verbose_name='Файлы/ссылки')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='crm_strategic_projects.projectstage')),
            ],
            options={
                'verbose_name': 'Результат этапа',
                'verbose_name_plural': 'Результаты этапов',
                'ordering': ['-added_date'],
            },
        ),
        migrations.CreateModel(
            name='StrategicProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название проекта')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код проекта')),
                ('goal', models.TextField(verbose_name='Цель проекта')),
                ('tasks', models.TextField(verbose_name='Задачи проекта')),
                ('planned_results', models.JSONField(default=list, verbose_name='Планируемые результаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('planned_start_date', models.DateField(verbose_name='Плановая дата начала')),
                ('planned_end_date', models.DateField(verbose_name='Плановая дата окончания')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата начала')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата окончания')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('on_approval', 'На утверждении'), ('rejected', 'Отклонен'), ('approved', 'Утвержден'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус проекта')),
                ('requires_budget', models.BooleanField(default=False, verbose_name='Требуется бюджет')),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Общий бюджет')),
                ('rejection_comment', models.TextField(blank=True, verbose_name='Комментарий при отклонении')),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_projects', to=settings.AUTH_USER_MODEL, verbose_name='Куратор проекта')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_projects', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик проекта')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_projects', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель проекта')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='crm_strategic_projects.programtopic')),
            ],
            options={
                'verbose_name': 'Стратегический проект',
                'verbose_name_plural': 'Стратегические проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='projectstage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm_strategic_projects.strategicproject'),
        ),
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('monthly', 'Месячный'), ('intermediate', 'Промежуточный'), ('final', 'Итоговый')], max_length=20, verbose_name='Тип отчета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('content', models.TextField(verbose_name='Содержание отчета')),
                ('approval_status', models.CharField(choices=[('draft', 'Черновик'), ('on_approval', 'На согласовании'), ('approved', 'Согласован'), ('rejected', 'Отклонен')], default='draft', max_length=20, verbose_name='Статус согласования')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('attachments', models.JSONField(default=list, verbose_name='Прикрепленные файлы')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='crm_strategic_projects.projectstage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='crm_strategic_projects.strategicproject')),
            ],
            options={
                'verbose_name': 'Отчет по проекту',
                'verbose_name_plural': 'Отчеты по проектам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('description', models.TextField(verbose_name='Описание изменения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Старое значение')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Новое значение')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='crm_strategic_projects.strategicproject')),
            ],
            options={
                'verbose_name': 'История изменений',
                'verbose_name_plural': 'История изменений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='programtopic',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_link', to='crm_strategic_projects.strategicproject'),
        ),
        migrations.CreateModel(
            name='StageExecutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'Основной исполнитель'), ('assistant', 'Помощник'), ('consultant', 'Консультант')], default='main', max_length=20, verbose_name='Роль в этапе')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executors', to='crm_strategic_projects.projectstage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Исполнитель этапа',
                'verbose_name_plural': 'Исполнители этапов',
                'unique_together': {('stage', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='projectstage',
            unique_together={('project', 'order_number')},
        ),
        migrations.AlterUniqueTogether(
            name='programtopic',
            unique_together={('program', 'direction_code', 'topic_number')},
        ),
    ]
