# Generated by Django 5.2.3 on 2025-06-29 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_strategic_projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategic_project_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stageexecutor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_stage_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='strategicproject',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategic_curated_projects', to=settings.AUTH_USER_MODEL, verbose_name='Куратор проекта'),
        ),
        migrations.AlterField(
            model_name='strategicproject',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategic_customer_projects', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик проекта'),
        ),
        migrations.AlterField(
            model_name='strategicproject',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategic_led_projects', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель проекта'),
        ),
    ]
