# Generated by Django 5.2.3 on 2025-07-01 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_strategic_projects', '0002_alter_projecthistory_user_alter_stageexecutor_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_project', models.CharField(max_length=50, verbose_name='Роль в проекте')),
                ('workload_percentage', models.IntegerField(default=0, verbose_name='Процент загрузки')),
                ('start_date', models.DateField(verbose_name='Дата начала участия')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания участия')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_workload', to='crm_strategic_projects.strategicproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_workload', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Загруженность сотрудника',
                'verbose_name_plural': 'Загруженность сотрудников',
            },
        ),
        migrations.CreateModel(
            name='UserProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор СтрПр'), ('curator_sp', 'Куратор СтрПр'), ('expert_group', 'Экспертная группа'), ('expert_lead', 'Руководитель ЭГ'), ('project_lead', 'Руководитель проекта'), ('customer', 'Заказчик проекта')], max_length=20, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_project_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Роль пользователя в СтрПр',
                'verbose_name_plural': 'Роли пользователей в СтрПр',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
