# Generated by Django 5.2.3 on 2025-07-05 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_strategic_projects', '0003_employeeworkload_userprojectrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('status_change', 'Изменение статуса'), ('approval_required', 'Требуется утверждение'), ('project_approved', 'Проект утвержден'), ('project_rejected', 'Проект отклонен'), ('deadline_approaching', 'Приближается срок'), ('task_assigned', 'Назначена задача'), ('stage_completed', 'Этап завершен'), ('comment_added', 'Добавлен комментарий'), ('project_started', 'Проект запущен'), ('project_completed', 'Проект завершен')], max_length=50, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='crm_strategic_projects.strategicproject', verbose_name='Проект')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление проекта',
                'verbose_name_plural': 'Уведомления проектов',
                'ordering': ['-created_at'],
            },
        ),
    ]
