# Generated by Django 5.2.4 on 2025-07-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('salary_from', models.IntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.IntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('salary_currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Валюта зарплаты')),
                ('salary_gross', models.BooleanField(default=True, verbose_name='Зарплата до вычета налогов')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Требования')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='Обязанности')),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип занятости')),
                ('experience_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Уровень опыта')),
                ('skills', models.JSONField(default=list, verbose_name='Навыки')),
                ('key_skills', models.JSONField(default=list, verbose_name='Ключевые навыки')),
                ('hh_id', models.CharField(max_length=50, unique=True, verbose_name='ID вакансии на HH')),
                ('url', models.URLField(verbose_name='Ссылка на вакансию')),
                ('company_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на компанию')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['title'], name='vacancies_p_title_58635d_idx'), models.Index(fields=['company_name'], name='vacancies_p_company_d90742_idx'), models.Index(fields=['city'], name='vacancies_p_city_176a9d_idx'), models.Index(fields=['published_at'], name='vacancies_p_publish_b8da66_idx'), models.Index(fields=['hh_id'], name='vacancies_p_hh_id_4207eb_idx')],
            },
        ),
    ]
