# Generated by Django 5.2.4 on 2025-07-18 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_parser_headhunter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='Номер версии')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('salary_from', models.IntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.IntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('salary_currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Валюта зарплаты')),
                ('salary_gross', models.BooleanField(default=True, verbose_name='Зарплата до вычета налогов')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Требования')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='Обязанности')),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип занятости')),
                ('experience_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Уровень опыта')),
                ('skills', models.JSONField(default=list, verbose_name='Навыки')),
                ('key_skills', models.JSONField(default=list, verbose_name='Ключевые навыки')),
                ('schedule_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='График работы')),
                ('professional_role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Профессиональная роль')),
                ('employer_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID работодателя')),
                ('employer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название работодателя')),
                ('employer_trusted', models.BooleanField(default=False, verbose_name='Проверенный работодатель')),
                ('employer_blacklisted', models.BooleanField(default=False, verbose_name='Работодатель в черном списке')),
                ('premium', models.BooleanField(default=False, verbose_name='Премиум вакансия')),
                ('has_test', models.BooleanField(default=False, verbose_name='Есть тестовое задание')),
                ('response_letter_required', models.BooleanField(default=False, verbose_name='Требуется сопроводительное письмо')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания версии')),
            ],
            options={
                'verbose_name': 'Версия вакансии',
                'verbose_name_plural': 'Версии вакансий',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='alternate_url',
            field=models.URLField(blank=True, null=True, verbose_name='Альтернативная ссылка'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='apply_alternate_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка для отклика'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='current_version',
            field=models.IntegerField(default=1, verbose_name='Текущая версия'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employer_blacklisted',
            field=models.BooleanField(default=False, verbose_name='Работодатель в черном списке'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employer_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID работодателя'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название работодателя'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employer_trusted',
            field=models.BooleanField(default=False, verbose_name='Проверенный работодатель'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='has_test',
            field=models.BooleanField(default=False, verbose_name='Есть тестовое задание'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='premium',
            field=models.BooleanField(default=False, verbose_name='Премиум вакансия'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='professional_role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Профессиональная роль'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='response_letter_required',
            field=models.BooleanField(default=False, verbose_name='Требуется сопроводительное письмо'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='schedule_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='График работы'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['employer_id'], name='vacancies_p_employe_d56dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['current_version'], name='vacancies_p_current_ce01b8_idx'),
        ),
        migrations.AddField(
            model_name='vacancyversion',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='vacancies_parser_headhunter.vacancy', verbose_name='Вакансия'),
        ),
        migrations.AddIndex(
            model_name='vacancyversion',
            index=models.Index(fields=['vacancy', 'version_number'], name='vacancies_p_vacancy_51a7df_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancyversion',
            index=models.Index(fields=['created_at'], name='vacancies_p_created_8c9ac7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vacancyversion',
            unique_together={('vacancy', 'version_number')},
        ),
    ]
