# Generated by Django 5.2.4 on 2025-07-18 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_parser_headhunter', '0002_vacancyversion_vacancy_alternate_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancyversion',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='city',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='employer_blacklisted',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='employer_id',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='employer_name',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='employer_trusted',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='has_test',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='key_skills',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='premium',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='professional_role',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='response_letter_required',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='responsibilities',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='salary_currency',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='salary_from',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='salary_gross',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='salary_to',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='schedule_type',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='vacancyversion',
            name='title',
        ),
        migrations.AddField(
            model_name='vacancyversion',
            name='change_summary',
            field=models.TextField(blank=True, null=True, verbose_name='Описание изменений'),
        ),
        migrations.CreateModel(
            name='VacancyChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Название поля')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Новое значение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='vacancies_parser_headhunter.vacancy', verbose_name='Вакансия')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='vacancies_parser_headhunter.vacancyversion', verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'История изменений вакансии',
                'verbose_name_plural': 'История изменений вакансий',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vacancy', 'version'], name='vacancies_p_vacancy_a33263_idx'), models.Index(fields=['field_name'], name='vacancies_p_field_n_a5a6a6_idx'), models.Index(fields=['created_at'], name='vacancies_p_created_65b063_idx')],
            },
        ),
    ]
