# Generated by Django 5.1.6 on 2025-04-12 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_shortcodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsshortcodetemplate',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms_shortcodes.cmsshortcodetemplate'),
        ),
        migrations.AddField(
            model_name='cmsshortcodetemplate',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CmsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CmsShortcodeInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_list', models.JSONField(blank=True, default=list)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('position', models.PositiveIntegerField(default=0)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(blank=True, help_text='Если это корневой шорткод страницы, page не null', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='cms_shortcodes.cmspage')),
                ('parent', models.ForeignKey(blank=True, help_text='Если шорткод вложен в другой шорткод', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms_shortcodes.cmsshortcodeinstance')),
                ('template', models.ForeignKey(help_text='Шаблон компонента', on_delete=django.db.models.deletion.PROTECT, to='cms_shortcodes.cmsshortcodetemplate')),
            ],
        ),
    ]
