# Generated by Django 5.1.6 on 2025-04-12 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_shortcodes', '0002_cmsshortcodetemplate_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmsshortcodeinstance',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='cmsshortcodetemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cmsshortcodeinstance',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='cms_shortcodes.cmspage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cmsshortcodeinstance',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms_shortcodes.cmsshortcodeinstance'),
        ),
        migrations.AlterField(
            model_name='cmsshortcodetemplate',
            name='content',
            field=models.TextField(blank=True, help_text='Опциональный HTML или текст'),
        ),
        migrations.AddConstraint(
            model_name='cmsshortcodeinstance',
            constraint=models.UniqueConstraint(fields=('parent', 'position'), name='unique_position_per_parent'),
        ),
    ]
