# Generated by Django 5.1.7 on 2025-05-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_shortcodes', '0003_alter_cmsshortcodeinstance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsshortcodetemplate',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Имя иконки из lucide-vue-next', max_length=100),
        ),
    ]
