# Generated by Django 5.1.7 on 2025-05-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_shortcodes', '0004_cmsshortcodetemplate_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsshortcodetemplate',
            name='allow_children',
            field=models.BooleanField(default=False, help_text='Можно ли вкладывать в этот компонент другие компоненты'),
        ),
    ]
