# Generated by Django 5.1.7 on 2025-05-05 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_shortcodes', '0005_cmsshortcodetemplate_allow_children'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmsShortcodeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='cmsshortcodetemplate',
            name='component_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='cms_shortcodes.cmsshortcodecategory'),
        ),
    ]
