# Generated by Django 5.2.2 on 2025-06-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_shortcodes', '0007_alter_cmsshortcodetemplate_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsshortcodeinstance',
            name='uid',
            field=models.CharField(db_index=True, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
