# Generated by Django 5.2.2 on 2025-06-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_shortcodes', '0008_cmsshortcodeinstance_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsshortcodeinstance',
            name='allow_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cmsshortcodeinstance',
            name='icon_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cmsshortcodeinstance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
