# Generated by Django 5.2.3 on 2025-06-15 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_shortcodes', '0009_cmsshortcodeinstance_allow_children_and_more'),
        ('settings', '0007_useravatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmspage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='settings.category', verbose_name='Категория страницы'),
        ),
        migrations.AddField(
            model_name='cmspage',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pages', to='settings.tag', verbose_name='Теги страницы'),
        ),
    ]
