# Generated by Django 5.2.3 on 2025-06-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_shortcodes', '0010_cmspage_category_cmspage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmspage',
            name='is_homepage',
            field=models.BooleanField(default=False, help_text='Является ли эта страница главной', verbose_name='Главная страница'),
        ),
    ]
