# Generated by Django 5.2.3 on 2025-06-16 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_shortcodes', '0011_cmspage_is_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms_shortcodes.cmsshortcodetemplate')),
                ('header_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms_shortcodes.cmsshortcodetemplate')),
            ],
            options={
                'verbose_name': 'Глобальный Layout',
                'verbose_name_plural': 'Глобальный Layout',
                'default_permissions': (),
            },
        ),
    ]
