# Generated by Django 5.2.3 on 2025-06-16 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_shortcodes', '0012_sitelayout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitelayout',
            options={'verbose_name': 'Глобальный Layout', 'verbose_name_plural': 'Глобальный Layout'},
        ),
    ]
