# Generated by Django 5.2.3 on 2025-06-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_shortcodes', '0013_alter_sitelayout_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelayout',
            name='menu_pages',
            field=models.ManyToManyField(blank=True, related_name='+', to='cms_shortcodes.cmspage'),
        ),
    ]
