# Generated by Django 5.2.3 on 2025-06-16 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_shortcodes', '0014_sitelayout_menu_pages'),
        ('settings', '0007_useravatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cmspage',
            name='category_index',
            field=models.BooleanField(default=False, help_text='Если True — страница открывается по URL самой категории'),
        ),
        migrations.AddConstraint(
            model_name='cmspage',
            constraint=models.UniqueConstraint(condition=models.Q(('category_index', True)), fields=('category',), name='unique_category_index'),
        ),
    ]
