# Generated by Django 5.2.3 on 2025-06-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_shortcodes', '0015_cmspage_category_index_cmspage_unique_category_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmspage',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
