# Generated by Django 5.2.3 on 2025-06-29 18:48

from django.db import migrations


def create_initial_statuses_and_priorities(apps, schema_editor):
    """Создание начальных статусов и приоритетов"""
    ProjectStatus = apps.get_model('crm', 'ProjectStatus')
    ProjectPriority = apps.get_model('crm', 'ProjectPriority')
    TaskStatus = apps.get_model('crm', 'TaskStatus')
    TaskPriority = apps.get_model('crm', 'TaskPriority')
    
    # Статусы проектов
    project_statuses = [
        {'name': 'Планирование', 'code': 'planning', 'color': '#17a2b8', 'order': 1, 'is_default': True},
        {'name': 'Активный', 'code': 'active', 'color': '#28a745', 'order': 2},
        {'name': 'Приостановлен', 'code': 'on_hold', 'color': '#ffc107', 'order': 3},
        {'name': 'Завершен', 'code': 'completed', 'color': '#6c757d', 'order': 4, 'is_final': True},
        {'name': 'Отменен', 'code': 'cancelled', 'color': '#dc3545', 'order': 5, 'is_final': True},
    ]
    
    for status_data in project_statuses:
        ProjectStatus.objects.get_or_create(
            code=status_data['code'],
            defaults=status_data
        )
    
    # Приоритеты проектов
    project_priorities = [
        {'name': 'Низкий', 'code': 'low', 'color': '#6f42c1', 'level': 1},
        {'name': 'Средний', 'code': 'medium', 'color': '#007bff', 'level': 2, 'is_default': True},
        {'name': 'Высокий', 'code': 'high', 'color': '#fd7e14', 'level': 3},
        {'name': 'Срочный', 'code': 'urgent', 'color': '#dc3545', 'level': 4},
    ]
    
    for priority_data in project_priorities:
        ProjectPriority.objects.get_or_create(
            code=priority_data['code'],
            defaults=priority_data
        )
    
    # Статусы задач
    task_statuses = [
        {'name': 'К выполнению', 'code': 'todo', 'color': '#6c757d', 'order': 1, 'is_default': True, 'kanban_column': 'todo'},
        {'name': 'В работе', 'code': 'in_progress', 'color': '#007bff', 'order': 2, 'kanban_column': 'in_progress'},
        {'name': 'На проверке', 'code': 'review', 'color': '#ffc107', 'order': 3, 'kanban_column': 'review'},
        {'name': 'Выполнено', 'code': 'done', 'color': '#28a745', 'order': 4, 'is_final': True, 'kanban_column': 'done'},
        {'name': 'Отменено', 'code': 'cancelled', 'color': '#dc3545', 'order': 5, 'is_final': True},
    ]
    
    for status_data in task_statuses:
        TaskStatus.objects.get_or_create(
            code=status_data['code'],
            defaults=status_data
        )
    
    # Приоритеты задач
    task_priorities = [
        {'name': 'Низкий', 'code': 'low', 'color': '#6f42c1', 'level': 1},
        {'name': 'Средний', 'code': 'medium', 'color': '#007bff', 'level': 2, 'is_default': True},
        {'name': 'Высокий', 'code': 'high', 'color': '#fd7e14', 'level': 3},
        {'name': 'Срочный', 'code': 'urgent', 'color': '#dc3545', 'level': 4},
    ]
    
    for priority_data in task_priorities:
        TaskPriority.objects.get_or_create(
            code=priority_data['code'],
            defaults=priority_data
        )


def reverse_create_initial_statuses_and_priorities(apps, schema_editor):
    """Откат миграции - удаление начальных данных"""
    ProjectStatus = apps.get_model('crm', 'ProjectStatus')
    ProjectPriority = apps.get_model('crm', 'ProjectPriority')
    TaskStatus = apps.get_model('crm', 'TaskStatus')
    TaskPriority = apps.get_model('crm', 'TaskPriority')
    
    # Удаляем только те записи, которые создали мы
    initial_codes = ['planning', 'active', 'on_hold', 'completed', 'cancelled', 'low', 'medium', 'high', 'urgent', 'todo', 'in_progress', 'review', 'done']
    
    ProjectStatus.objects.filter(code__in=initial_codes).delete()
    ProjectPriority.objects.filter(code__in=initial_codes).delete()
    TaskStatus.objects.filter(code__in=initial_codes).delete()
    TaskPriority.objects.filter(code__in=initial_codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_projectpriority_projectstatus_taskpriority_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_statuses_and_priorities,
            reverse_create_initial_statuses_and_priorities
        ),
    ]
