# Generated by Django 5.2.3 on 2025-06-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20250629_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstatus',
            name='kanban_column',
        ),
    ]
