# Generated by Django 5.2.5 on 2025-08-11 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_team_and_project_team_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('assignee', 'Исполнитель'), ('reviewer', 'Ревьюер')], default='assignee', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Назначение задачи',
                'verbose_name_plural': 'Назначения задач',
            },
        ),
        migrations.CreateModel(
            name='TaskTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Связь дерева задач',
                'verbose_name_plural': 'Связи дерева задач',
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='crm_task_project_482b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'due_date'], name='crm_task_project_1891ac_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'parent'], name='crm_task_project_f1bd1b_idx'),
        ),
        migrations.AddField(
            model_name='taskassignee',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskassignee',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee_links', to='crm.task'),
        ),
        migrations.AddField(
            model_name='taskassignee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktree',
            name='ancestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendant_entries', to='crm.task'),
        ),
        migrations.AddField(
            model_name='tasktree',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_entries', to='crm.task'),
        ),
        migrations.AlterUniqueTogether(
            name='taskassignee',
            unique_together={('task', 'user', 'role')},
        ),
        migrations.AddIndex(
            model_name='tasktree',
            index=models.Index(fields=['task', 'ancestor'], name='crm_tasktre_task_id_420988_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktree',
            index=models.Index(fields=['ancestor', 'depth'], name='crm_tasktre_ancesto_64910b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tasktree',
            unique_together={('task', 'ancestor')},
        ),
    ]
