# Generated by Django 5.2.4 on 2025-07-24 19:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('original_video', models.FileField(upload_to='video_analysis/original/', verbose_name='Исходное видео')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершен'), ('failed', 'Ошибка'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало обработки')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение обработки')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='video_analysis/audio/', verbose_name='Аудио файл')),
                ('subtitles_file', models.FileField(blank=True, null=True, upload_to='video_analysis/subtitles/', verbose_name='Файл субтитров')),
                ('output_video', models.FileField(blank=True, null=True, upload_to='video_analysis/output/', verbose_name='Видео с субтитрами')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Длительность (секунды)')),
                ('subtitle_count', models.IntegerField(default=0, verbose_name='Количество субтитров')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID задачи Celery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Видео-анализ',
                'verbose_name_plural': 'Видео-анализы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubtitleSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_number', models.IntegerField(verbose_name='Номер сегмента')),
                ('start_time', models.CharField(max_length=20, verbose_name='Время начала')),
                ('end_time', models.CharField(max_length=20, verbose_name='Время окончания')),
                ('russian_text', models.TextField(verbose_name='Русский текст')),
                ('french_text', models.TextField(verbose_name='Французский текст')),
                ('video_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_segments', to='video_analysis.videoanalysis', verbose_name='Видео-анализ')),
            ],
            options={
                'verbose_name': 'Сегмент субтитров',
                'verbose_name_plural': 'Сегменты субтитров',
                'ordering': ['segment_number'],
            },
        ),
    ]
