# Generated by Django 5.2.4 on 2025-07-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoanalysis',
            name='audio_file',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к аудио файлу'),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='output_video',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к видео с субтитрами'),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='subtitles_file',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к файлу субтитров'),
        ),
    ]
