# Generated by Django 5.1.7 on 2025-04-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_analysis_bi_connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connector_type',
            field=models.CharField(choices=[('postgres', 'PostgreSQL'), ('clickhouse', 'ClickHouse'), ('mssql', 'Microsoft SQL Server'), ('file', 'Файл')], max_length=50),
        ),
    ]
