# Generated by Django 5.1.7 on 2025-05-11 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertSystemOrientationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertSystemOrientationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название теста')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertSystemQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertSystemRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Роль')),
                ('description', models.TextField(verbose_name='Описание роли')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertSystemSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Навык')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertSystemStudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название группы')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertsystemCompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('description', models.TextField(blank=True, verbose_name='Описание компании')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('contact_person', models.CharField(max_length=150, verbose_name='Контактное лицо')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактный E-mail')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Аккаунт подтверждён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь-работодатель')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertSystemOrientationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст ответа')),
                ('weight', models.IntegerField(default=0, verbose_name='Вес ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='expert_system.expertsystemorientationquestion', verbose_name='Вопрос')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system.expertsystemrole', verbose_name='Роль для начисления баллов')),
            ],
        ),
        migrations.AddField(
            model_name='expertsystemorientationquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='expert_system.expertsystemorientationtest', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='ExpertSystemAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='expert_system.expertsystemquestion', verbose_name='Вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertSystemStudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('has_experience', models.BooleanField(default=False, verbose_name='Есть опыт в IT')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь-студент')),
                ('study_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expert_system.expertsystemstudygroup', verbose_name='Учебная группа')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertSystemOrientationTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения')),
                ('best_score', models.FloatField(blank=True, null=True, verbose_name='Процент соответствия')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='expert_system.expertsystemorientationtest', verbose_name='Тест')),
                ('best_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expert_system.expertsystemrole', verbose_name='Рекомендуемая роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientation_results', to='expert_system.expertsystemstudentprofile', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertSystemTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название теста')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='expert_system.expertsystemskill', verbose_name='Навык')),
            ],
        ),
        migrations.AddField(
            model_name='expertsystemquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='expert_system.expertsystemtest', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='ExpertSystemTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Баллы')),
                ('passed', models.BooleanField(default=False, verbose_name='Пройдено')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system.expertsystemtest', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system.expertsystemstudentprofile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
            },
        ),
        migrations.CreateModel(
            name='ExpertSystemTrajectoryStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок шага')),
                ('description', models.TextField(verbose_name='Описание шага')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='expert_system.expertsystemrole', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Шаг траектории',
                'verbose_name_plural': 'Шаги траектории',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExpertSystemVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок вакансии')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='expert_system.expertsystemcompanyprofile', verbose_name='Работодатель')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertSystemCandidateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи заявки')),
                ('match_score', models.FloatField(blank=True, null=True, verbose_name='Коэффициент совпадения')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='expert_system.expertsystemstudentprofile', verbose_name='Кандидат')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='expert_system.expertsystemvacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Заявка кандидата',
                'verbose_name_plural': 'Заявки кандидатов',
            },
        ),
        migrations.CreateModel(
            name='ExpertSystemVacancySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Обязательный навык')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system.expertsystemskill', verbose_name='Навык')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system.expertsystemvacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Навык вакансии',
                'verbose_name_plural': 'Навыки вакансии',
                'unique_together': {('vacancy', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='expertsystemvacancy',
            name='required_skills',
            field=models.ManyToManyField(related_name='vacancies', through='expert_system.ExpertSystemVacancySkill', to='expert_system.expertsystemskill', verbose_name='Требуемые навыки'),
        ),
        migrations.CreateModel(
            name='ExpertSystemOrientationUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system.expertsystemorientationanswer', verbose_name='Выбранный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system.expertsystemorientationquestion', verbose_name='Вопрос')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='expert_system.expertsystemorientationtestresult', verbose_name='Результат теста')),
            ],
            options={
                'verbose_name': 'Ответ на ориентационный вопрос',
                'verbose_name_plural': 'Ответы на ориентационные вопросы',
                'unique_together': {('result', 'question')},
            },
        ),
        migrations.CreateModel(
            name='ExpertSystemUserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unconfirmed', 'Неподтверждён'), ('confirmed', 'Подтверждён')], default='unconfirmed', max_length=20, verbose_name='Статус навыка')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='expert_system.expertsystemskill', verbose_name='Навык')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='expert_system.expertsystemstudentprofile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Навык пользователя',
                'verbose_name_plural': 'Навыки пользователей',
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
