# Generated by Django 5.1.6 on 2025-05-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertsystemstudentprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='expertsystemstudentprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон'),
        ),
    ]
