# Generated by Django 5.1.4 on 2025-05-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system', '0002_expertsystemstudentprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertsystemtest',
            name='descriptions',
            field=models.TextField(default='', verbose_name='описание'),
        ),
    ]
