# Generated by Django 5.1.4 on 2025-05-19 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system', '0003_expertsystemtest_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertSystemTestUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system.expertsystemanswer', verbose_name='Выбранный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system.expertsystemquestion', verbose_name='Вопрос')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='expert_system.expertsystemtest', verbose_name='Результат теста')),
            ],
            options={
                'verbose_name': 'Ответ на тестовые вопросы',
                'verbose_name_plural': 'Ответы на тестовые вопросы',
                'unique_together': {('result', 'question')},
            },
        ),
    ]
