# Generated by Django 5.1.7 on 2025-06-04 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system', '0003_expertsystemtest_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertsystemstudentprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expert_system.expertsystemrole', verbose_name='Выбранная профессия'),
        ),
    ]
