# Generated by Django 5.1.7 on 2025-06-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system', '0004_expertsystemstudentprofile_role'),
        ('expert_system', '0005_alter_expertsystemtestuseranswer_result'),
    ]

    operations = [
    ]
