# Generated by Django 5.1.7 on 2025-06-07 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system', '0006_merge_20250607_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertSystemCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='expert_system.expertsystemrole', verbose_name='Профессия (роль)')),
            ],
        ),
    ]
