# Generated by Django 5.2.2 on 2025-06-08 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system', '0007_expertsystemcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertsystemcourse',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='expert_system.expertsystemcompanyprofile', verbose_name='Работодатель'),
            preserve_default=False,
        ),
    ]
