# Generated by Django 5.2.3 on 2025-06-16 21:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_usd', models.CharField(max_length=50)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('name_rub', models.CharField(blank=True, max_length=50, null=True)),
                ('price_rub', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'unique_together': {('name_usd', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='CryptoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('price_usd', models.DecimalField(decimal_places=8, max_digits=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['name', 'timestamp'], name='assets_anal_name_6d4b71_idx')],
                'unique_together': {('name', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('url', models.URLField(db_index=True, max_length=1024, unique=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('relevant_coins', models.JSONField(blank=True, db_index=True, default=list)),
                ('sentiment_score', models.FloatField(blank=True, help_text='Числовая оценка тональности', null=True)),
                ('sentiment_label', models.CharField(blank=True, choices=[('positive', 'Позитивная'), ('negative', 'Негативная'), ('neutral', 'Нейтральная'), ('skipped', 'Пропущено')], db_index=True, help_text='Категориальная оценка тональности (positive/negative/neutral)', max_length=10, null=True)),
                ('manual_label', models.CharField(blank=True, choices=[('positive', 'Позитивная'), ('negative', 'Негативная'), ('neutral', 'Нейтральная')], help_text='Ручная разметка тональности (хорошая/плохая/нейтральная новость)', max_length=10, null=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['published_at'], name='assets_anal_publish_838666_idx'), models.Index(fields=['sentiment_label'], name='assets_anal_sentime_51f8ec_idx'), models.Index(fields=['manual_label'], name='assets_anal_manual__49350b_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, help_text='Биржевой тикер акции', max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Дата и время цены')),
                ('price_usd', models.DecimalField(blank=True, decimal_places=8, help_text='Цена в долларах США', max_digits=20, null=True)),
                ('price_rub', models.DecimalField(blank=True, decimal_places=8, help_text='Цена в российских рублях', max_digits=20, null=True)),
                ('close_price', models.DecimalField(decimal_places=8, help_text='Цена закрытия (основное поле цены)', max_digits=20)),
                ('volume', models.BigIntegerField(blank=True, help_text='Объем торгов', null=True)),
            ],
            options={
                'verbose_name': 'Цена акции',
                'verbose_name_plural': 'Цены акций',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ticker', 'timestamp'], name='assets_anal_ticker_c2d2e0_idx')],
                'unique_together': {('ticker', 'timestamp')},
            },
        ),
    ]
