# Generated by Django 5.2.4 on 2025-07-30 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('salary_from', models.IntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.IntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('salary_currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Валюта зарплаты')),
                ('salary_gross', models.BooleanField(default=True, verbose_name='Зарплата до вычета налогов')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Требования')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='Обязанности')),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип занятости')),
                ('experience_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Уровень опыта')),
                ('qualification', models.CharField(blank=True, max_length=100, null=True, verbose_name='Квалификация')),
                ('skills', models.JSONField(default=list, verbose_name='Навыки')),
                ('specializations', models.JSONField(default=list, verbose_name='Специализации')),
                ('divisions', models.JSONField(default=list, verbose_name='Подразделения')),
                ('habr_id', models.CharField(max_length=50, unique=True, verbose_name='ID вакансии на Хабр Карьере')),
                ('url', models.URLField(verbose_name='Ссылка на вакансию')),
                ('company_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на компанию')),
                ('company_alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='Алиас компании')),
                ('schedule_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='График работы')),
                ('marked', models.BooleanField(default=False, verbose_name='Помеченная вакансия')),
                ('company_logo_url', models.URLField(blank=True, null=True, verbose_name='Логотип компании')),
                ('premium', models.BooleanField(default=False, verbose_name='Премиум вакансия')),
                ('has_test', models.BooleanField(default=False, verbose_name='Есть тестовое задание')),
                ('response_letter_required', models.BooleanField(default=False, verbose_name='Требуется сопроводительное письмо')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('current_version', models.IntegerField(default=1, verbose_name='Текущая версия')),
            ],
            options={
                'verbose_name': 'Вакансия Хабр Карьера',
                'verbose_name_plural': 'Вакансии Хабр Карьера',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['title'], name='vacancies_p_title_abdde4_idx'), models.Index(fields=['company_name'], name='vacancies_p_company_518ca5_idx'), models.Index(fields=['city'], name='vacancies_p_city_534235_idx'), models.Index(fields=['published_at'], name='vacancies_p_publish_99d469_idx'), models.Index(fields=['habr_id'], name='vacancies_p_habr_id_6dc4b2_idx'), models.Index(fields=['current_version'], name='vacancies_p_current_b2673f_idx')],
            },
        ),
        migrations.CreateModel(
            name='VacancyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='Номер версии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания версии')),
                ('change_summary', models.TextField(blank=True, null=True, verbose_name='Описание изменений')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='vacancies_parser_habr_career.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Версия вакансии Хабр Карьера',
                'verbose_name_plural': 'Версии вакансий Хабр Карьера',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='VacancyChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Название поля')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Новое значение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='vacancies_parser_habr_career.vacancy', verbose_name='Вакансия')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='vacancies_parser_habr_career.vacancyversion', verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'История изменений вакансии Хабр Карьера',
                'verbose_name_plural': 'История изменений вакансий Хабр Карьера',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vacancyversion',
            index=models.Index(fields=['vacancy', 'version_number'], name='vacancies_p_vacancy_a57fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancyversion',
            index=models.Index(fields=['created_at'], name='vacancies_p_created_6d9b9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vacancyversion',
            unique_together={('vacancy', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='vacancychangehistory',
            index=models.Index(fields=['vacancy', 'created_at'], name='vacancies_p_vacancy_c0880c_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancychangehistory',
            index=models.Index(fields=['field_name'], name='vacancies_p_field_n_a202d4_idx'),
        ),
    ]
