# Generated by Django 5.1.6 on 2025-02-24 10:58

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('location_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('City', 'Местность является городом'), ('Region', 'Местность является регионом страны'), ('Country', 'Местность является страной'), ('City Region', 'Местность является районом города'), ('Point', 'Местность представлена координатами'), ('Continent', 'Местность представлена континентом')], max_length=60, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CountryCodeAdjacent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a2_code', models.CharField(max_length=5)),
                ('a3_code', models.CharField(max_length=5)),
                ('numeric', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_expansion.location')),
            ],
        ),
        migrations.CreateModel(
            name='BoundingBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom_left_latitude', models.FloatField()),
                ('bottom_left_longitude', models.FloatField()),
                ('upper_right_latitude', models.FloatField()),
                ('upper_right_longitude', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_expansion.location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_expansion.locationtype'),
        ),
    ]
