# Generated by Django 5.1.7 on 2025-05-12 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_expansion', '0005_add_bounding_boxes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=256)),
                ('date', models.DateTimeField()),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_expansion.fileupload')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_expansion.group')),
            ],
        ),
    ]
