# Generated by Django 5.1.7 on 2025-05-19 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_expansion', '0007_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField()),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cities_expansion.task')),
            ],
        ),
    ]
