# Generated by Django 5.1.7 on 2025-05-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_expansion', '0008_taskresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status_description',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
