# Generated by Django 5.1.7 on 2025-05-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_expansion', '0009_task_status_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status_description',
            field=models.TextField(),
        ),
    ]
